#!/usr/bin/env python3
"""The two analytic control domains for the sign study (prereg M2).

    .venv/bin/python study/tools/make_synth_sign_domains.py

Both domains use ONE generator; the only thing that differs is the
distribution of a single shape parameter. That is what makes them a control:
if the measured directions differ, the difference cannot come from anything
else in the construction.

The mechanism, stated before the numbers exist
----------------------------------------------
The detector scores a window as max|z|, i.e. DISTANCE from the healthy centre.
It is therefore not enough for an anomaly to "look different" — a shift in any
direction raises |z| and would push AUC above 0.5. The score can only fall
below 0.5 when the anomaly's features sit CLOSER to the healthy centre than a
typical healthy window does: a contraction, not a shift.

So the signal is an AR(1) process whose coefficient phi controls autocorrelation
(a shape property, which survives the per-window z-normalisation that erases
amplitude — the trap that a first smoke test fell into):

  healthy            phi ~ Uniform(0.20, 0.80)   -> features spread about 0.50
  synth_pos anomaly  phi = 0.95                  -> far outside that spread
  synth_neg anomaly  phi = 0.50                  -> exactly the healthy centre

PREDICTIONS, registered before the readout runs (prereg AMENDMENT 4):
  * synth_pos: AUC clearly ABOVE 0.5, CI-fest "aligned".
  * synth_neg: AUC BELOW 0.5, CI-fest "inverted" — the anomaly is more
    stereotyped than normal operation, so it looks *more* normal than normal.

synth_neg is the constructive counterexample: a domain where the inversion is
true by design, proving the direction is a property of the unobserved
alternative and cannot be recovered from healthy data alone.
"""
import hashlib
import json
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "data" / "signdomains"

N = 20 * 1024
N_FIT, N_EVAL = 40, 40
SEED = 0
PHI_LO, PHI_HI = 0.20, 0.80
PHI_CENTRE = 0.50
PHI_FAR = 0.95
BURN = 2000


def ar1(phi, rng, n=N):
    """AR(1) with unit-variance innovations. phi sets autocorrelation only."""
    e = rng.normal(0.0, 1.0, n + BURN)
    x = np.empty(n + BURN)
    x[0] = e[0]
    for i in range(1, n + BURN):
        x[i] = phi * x[i - 1] + e[i]
    return x[BURN:]


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def build(domain, phi_anomaly, prediction):
    dest = OUT / domain
    (dest / "fit").mkdir(parents=True, exist_ok=True)
    (dest / "eval").mkdir(parents=True, exist_ok=True)
    for old in list((dest / "fit").glob("*.npy")) + list((dest / "eval").glob("*.npy")):
        old.unlink()

    rng = np.random.default_rng(SEED)
    for i in range(N_FIT):
        phi = rng.uniform(PHI_LO, PHI_HI)
        np.save(dest / "fit" / f"h{i:03d}.npy", ar1(phi, rng))
    for i in range(N_EVAL):
        phi = rng.uniform(PHI_LO, PHI_HI)
        np.save(dest / "eval" / f"normal_{i:03d}.npy", ar1(phi, rng))
    for i in range(N_EVAL):
        np.save(dest / "eval" / f"anomaly_{i:03d}.npy", ar1(phi_anomaly, rng))

    files = {str(p.relative_to(dest)): sha256(p) for p in sorted(dest.rglob("*.npy"))}
    (dest / "manifest.json").write_text(json.dumps({
        "domain": domain,
        "source_url": "generated by study/tools/make_synth_sign_domains.py",
        "license": "same as this repository",
        "modality": "synthetic AR(1); phi controls autocorrelation, a shape "
                    "property that survives per-window z-normalisation",
        "fs_hz": 1, "channel": "0 = the only channel",
        "anomaly_mapping": (f"healthy and eval-normal draw phi ~ Uniform"
                            f"({PHI_LO}, {PHI_HI}); anomaly recordings use the "
                            f"fixed phi = {phi_anomaly}"),
        "prediction_registered_before_readout": prediction,
        "seed": SEED, "burn_in": BURN,
        "n_fit": N_FIT, "n_eval_normal": N_EVAL, "n_eval_anomaly": N_EVAL,
        "files": files,
    }, indent=2, sort_keys=True) + "\n")
    return len(files)


def main():
    n1 = build("synth_pos", PHI_FAR,
               "AUC clearly above 0.5, CI-fest aligned: the anomaly sits far "
               "outside the healthy spread, so max|z| rises")
    print(f"[synth_pos] {n1} recordings — predicted AUC > 0.5 (aligned)")
    n2 = build("synth_neg", PHI_CENTRE,
               "AUC below 0.5, CI-fest inverted: the anomaly sits exactly at "
               "the healthy centre, so max|z| falls below that of a typical "
               "healthy window")
    print(f"[synth_neg] {n2} recordings — predicted AUC < 0.5 (inverted)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
